namespace DataProvider.Providers.Cards.Amex.Dto
{
  public class AmexDealDetailsResponse
    {
    public object SupplierId { get; set; }
    public object Solek { get; set; }
    public object Info { get; set; }
    public object VoucherNumber { get; set; }
    public object SupplierName { get; set; }
    public object DealType { get; set; }
    public object Sector { get; set; }
    public object Address { get; set; }
    public object MoreInfo { get; set; }
    public object PhoneNumber { get; set; }
    public object Discount { get; set; }
    public object PurchaseTime { get; set; }
    public object SumBeforeDiscount { get; set; }
    public object DealSum { get; set; }
    public object City { get; set; }
    public object PaymentNumber { get; set; }
    public object NumberOfPayments { get; set; }
    public object State { get; set; }
    public object InterestSum { get; set; }
    public object InterestPercentage { get; set; }
    public object SumOfCompensation { get; set; }
    public object SumOfValueAddedTax { get; set; }
    public object ValueDate { get; set; }
    public object DateConversion { get; set; }
    public object CurrencyId { get; set; }
    public object SumDollar { get; set; }
    public object DollarTransferRate { get; set; }
    public object DollarTransferCommissionPercentage { get; set; }
    public object MoneyWithdrawalCommission { get; set; }
    public object CommissionDiscountPercentage { get; set; }
    public object CommissionDiscountSum { get; set; }
    public object IsError { get; set; }
    public object SaleName { get; set; }
    public object SecondSaleName { get; set; }
    public object SumOfFund { get; set; }
    public object IsInbound { get; set; }
    public object Moed { get; set; }
    public object VoucherNumberRatz { get; set; }
    public object ChargeSum { get; set; }
    public object IsShowPaymentsTable { get; set; }
    public object CommissionNetValue { get; set; }
    public object CommissionNetValueCurrency { get; set; }
    public object DealSumOutbound { get; set; }
    public object CurrencyIdOutbound { get; set; }
    public object DealSumOutboundInshekels { get; set; }
    public object CurrencyIdForCharge { get; set; }
    public object Linking { get; set; }
    public object SupplierNameIsracard { get; set; }
    public object PurchaseDateOutboundIsracard { get; set; }
    public object CanOrder { get; set; }
    public object DealCode { get; set; }
    public object SelectedDate { get; set; }
    public object MoedChiuvFull { get; set; }
    public object ChargeSumToDisplay { get; set; }
    public object IsThereData { get; set; }
    public object Stage { get; set; }
    public object ReturnCode { get; set; }
    public object Message { get; set; }
    public object DisplayProperties { get; set; }
    public int TablePageNum { get; set; }
    public bool IsCaptcha { get; set; }
    public bool IsButton { get; set; }
    public object SiteName { get; set; }
  }
}
